apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: Sample service
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: sample-service
  tags:
    - java
    - kafka-producer
    - spring-boot
  metrics:
    Availability:
      - bucket: SERVICE
        value: 99.50
    Latency:
      - bucket: LEAD_CREATE_API_P90
        value: 1
      - bucket: LEAD_CREATE_API_P90
        value: 3
      - bucket: UPDATE_CREATE_API_P90
        value: 2
      - bucket: UPDATE_CREATE_API_P99
        value: 5
    RPO:
      - bucket: SERVICE
        value: 15
    RTO:
      - bucket: SERVICE
        value: 30
  links:
    - url: https://gitlab.piramalfinance.com/services/backend-engg/lead-service/-/blob/master/README.md
      title: Gitlab Repository
      icon: gitlab
      type: lead-service
    - url: https://mypiramal.atlassian.net/wiki/spaces/PRF/pages/342786100/EMBEDDED+FINANCE
      title: Confluence
    - url: https://gitlab.piramalfinance.com/services/backend-engg/kyc-service/-/blob/master/swagger/swagger.yaml
      title: Swagger
    - url: https://grafana.piramalfinance.com/d/arSucxrnz/lead-service?orgId=1
      title: Grafana Dashboard
      icon: dashboard
      
spec:
  type: service
  owner: group:ef_team
  domain: Embedded Finance
  lifecycle: production
  members: ["manish.kapoor"]
  dependsOn:
    - resource:lead_db
    - component:lead-event-listner-service
  providesApis:
    - lead-create
    - lead-update
  consumesApis:
    - risk-decision


---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: lead-create
  description: Create Lead
  links:
    - url: https://gitlab.piramalfinance.com/services/backend-engg/kyc-service/-/blob/master/swagger/swagger.yaml#/manual-controller/manualUsingPOST
      title: swagger - api definition
    - url: https://mypiramal.atlassian.net/wiki/spaces/PRF/pages/400982669/Create+Lead+Update+Lead#Create-Lead
      title: Confluence Documentation
  metrics:
    Latency:
      - bucket: LEAD_CREATE_API_P90
        value: 1
      - bucket: LEAD_CREATE_API_P90
        value: 3
spec:
  type: REST
  lifecycle: production
  owner: group:partnership
  definition: |
    paths:
      /create:
        post:
          summary: create lead
    
---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: lead-update
  description: Update Lead
  links:
    - url: https://gitlab.piramalfinance.com/services/backend-engg/kyc-service/-/blob/master/swagger/swagger.yaml#/manual-controller/manualUsingPOST
      title: swagger - api definition
    - url: https://mypiramal.atlassian.net/wiki/spaces/PRF/pages/400982669/Create+Lead+Update+Lead#Update-Lead
      title: Confluence Documentation
  metrics:
    Latency:
      - bucket: LEAD_UPDATE_API_P90
        value: 2
      - bucket: LEAD_UPDATE_API_P90
        value: 5
spec:
  type: REST
  lifecycle: production
  owner: group:LBP
  definition: |
    paths:
      /create:
        put:
          summary: update lead
    
    
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: manish.kapoor
spec:
  memberOf: [ef_team]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ef_team
spec:
  type: team
  children: [partnership, LBP]
  
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: partnership
spec:
  type: team
  children: []
  parent: ef_team
  
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: LBP
spec:
  type: team
  children: []
  parent: ef_team
