apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: Sample service
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: sample-service
  tags:
    - java
    - kafka-producer
    - spring-boot
  metrics:
    Availability:
      - bucket: SERVICE
        value: 99.50
    Latency:
      - bucket: LEAD_CREATE_API_P90
        value: 1
      - bucket: LEAD_CREATE_API_P90
        value: 3
      - bucket: UPDATE_CREATE_API_P90
        value: 2
      - bucket: UPDATE_CREATE_API_P99
        value: 5
    RPO:
      - bucket: SERVICE
        value: 15
    RTO:
      - bucket: SERVICE
        value: 30
      
spec:
  type: service
  owner: user:manishkapoor108
  domain: Example
  lifecycle: poc
  members: ["manishkapoor108"]

---
    

